language: java
jdk:
  - oraclejdk8
script:
  - mvn test
after_success:
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn tomcat7:deploy"
  skip_cleanup: true